introduce release process for tool

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -6,24 +6,57 @@ on:
   push:
     branches:
       - dev
-      - master
+      - main
     tags:
       - "*"
 
 jobs:
-  # verify:
-  #   uses: idelchi/devenv/.github/workflows/devenv-actions.yml@dev
-  #   with:
-  #     image: idelchi/devenv:dev
+  verify:
+    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+    uses: idelchi/devenv/.github/workflows/devenv-actions.yml@dev
+    with:
+      image: idelchi/devenv:dev
+      devenv: .devenv
+
+  test:
+    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+    needs: verify
+    strategy:
+      matrix:
+        os:
+          - ubuntu-24.04
+          - windows-2022
+          - macos-14
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.23.2"
+          check-latest: true
+
+      - name: Test
+        shell: sh
+        run: |
+          [ "$(go run ./cmd/go-next-tag v1.1)" = "v1.2" ] || (echo "test `v1.1` (argument) failed" && exit 1)
+          [ "$(echo "v2.1" | go run ./cmd/go-next-tag)" = "v2.2" ] || (echo "test `v2.1` (piped) failed" && exit 1)
+          [ "$(echo "v2.1" | go run ./cmd/go-next-tag v3.1)" = "v3.2" ] || (echo "test `v2.1/v3.1` (piped & argument) failed" && exit 1)
+          [ "$(go run ./cmd/go-next-tag)" = "v0.0" ] || (echo "test `no-input` failed" && exit 1)
+
+          [ "$(go run ./cmd/go-next-tag --bump=major v1.1)" = "v2.0" ] || (echo "test (--bump=major) `v1.1` (argument) failed" && exit 1)
+          [ "$(echo "v2.1" | go run ./cmd/go-next-tag --bump=major)" = "v3.0" ] || (echo "test (--bump=major) `v2.1` (piped) failed" && exit 1)
+          [ "$(echo "v2.1" | go run ./cmd/go-next-tag --bump=major v3.1)" = "v4.0" ] || (echo "test (--bump=major) `v2.1/v3.1` (piped & argument) failed" && exit 1)
+          [ "$(go run ./cmd/go-next-tag --bump=major )" = "v0.0" ] || (echo "test (--bump=major) `no-input` failed" && exit 1)
 
   last-tag:
-    permissions:
-      contents: write
-      actions: write
+    needs: test
     runs-on: ubuntu-24.04
     if: github.ref == 'refs/heads/dev'
     outputs:
-      tag: ${{ steps.tag.outputs.LAST_TAG }}
+      tag: ${{ steps.tag.outputs.NEXT_TAG }}
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -38,9 +71,15 @@ jobs:
           echo "LAST_TAG=${LAST_TAG}" >> ${GITHUB_ENV}
           echo "LAST_TAG=${LAST_TAG}" >> ${GITHUB_OUTPUT}
 
+          NEXT_TAG=$(go run ./cmd/go-next-tag ${LAST_TAG})
+
+          echo "NEXT_TAG=${NEXT_TAG}" >> ${GITHUB_ENV}
+          echo "NEXT_TAG=${NEXT_TAG}" >> ${GITHUB_OUTPUT}
+
       - name: check-env
         run: |
           echo "The last tag is '${LAST_TAG}'"
+          echo "The next tag is '${NEXT_TAG}'"
 
   tag-prerelease:
     needs: last-tag
@@ -60,9 +99,13 @@ jobs:
           fetch-depth: 0
           fetch-tags: true
 
-      - name: delete ${{ env.TAG }} tag & release
+      - name: delete old pre-release
         run: |
           gh release list --json tagName,isPrerelease -q '.[] | select(.isPrerelease == true) | .tagName' | xargs -I {} gh release delete {}
+        continue-on-error: true
+
+      - name: delete ${{ env.TAG }} release
+        run: |
           gh release delete ${{ env.TAG }} --yes --cleanup-tag
         continue-on-error: true
 
@@ -84,10 +127,9 @@ jobs:
   cleanup:
     needs: tag-prerelease
     permissions:
-      contents: write
       actions: write
     runs-on: ubuntu-24.04
-    if: github.ref == 'refs/heads/dev'
+    if: github.ref == 'refs/heads/dev' && ${{ always() }}
     continue-on-error: true
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
